<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatch;
use Drupal\block\Entity\Block;

function govcms_subtheme_preprocess_paragraph__sitemap(&$variables) {
  $menu_name = "main";
  $menu_tree = \Drupal::service('menu.link_tree');

  $parameters = new \Drupal\Core\Menu\MenuTreeParameters();
  $parameters
    ->setMaxDepth(99);
  $tree = $menu_tree->load($menu_name, $parameters);
  $menu = $menu_tree->build($tree);
  $variables['sitemap'] = $menu;
}
